### ISSUE TITLE
Light up sample/note names as they are triggered

### ISSUE THREAD

**Issue by ViktorNova** [rncbc/drumkv1#10]
This would be AWESOME and super helpful, if the sample name/number/note name lit up in the list on the right as they are being triggered by MIDI.

In a large sample library, it is sometimes difficult to pin down what sample is responsible for a sound being triggered without a visual cue, and it's not always easy to go to the sequencer to hunt it down. This would help a lot (and would also look cool!)

A flash of highlight behind the text that was proportionate to the current output volume of the sample being played would be even cooler, but not necessary!

**Comment by rncbc** [comment]
@ViktorNova : something resembling a MIDI In LED on each key element is still in the plans.

**Comment by ViktorNova** [comment]
Awesome!! That is great to hear =)

**Comment by rncbc** [comment]
@ViktorNova : checkout [midi_in_led](https://github.com/rncbc/drumkv1/tree/midi_in_led) branch from the latest git head ;)

**Comment by rncbc** [comment]
@ViktorNova : now merged to git head master:
https://github.com/rncbc/drumkv1/commit/651539e

relevant change-log line:
- A MIDI In(put) status fake-LED is now featured on the
  bottom-left status bar, adding up to eye-candy as usual;
  also, each drum element key/sample now have their own
  fake-LED flashing on respective MIDI note-on/off events.

hth.
cheers

**Comment by ViktorNova** [comment]
WOW this is a game changer!!! Thank you. 

Might I suggest a slight improvement - adding a small amount of fade out time to the LED when the note-off is received, rather than switching the LED off immediately? It would make it a little easier to spot what notes are being triggered

**Comment by rncbc** [comment]
@ViktorNova : done:
-Timeout added to drum element note/key status LEDs turning off.   https://github.com/rncbc/drumkv1/commit/de288af

**Comment by ViktorNova** [comment]
Very cool. This is huge, thanks so much for taking input!
