### ISSUE TITLE
UI improvements to bypass volume envelope

### ISSUE THREAD

**Issue by ViktorNova** [rncbc/drumkv1#11]
In addition to bypassing the filter, this would be a great feature as well, as it is currently not possible to play a sample longer than a second or 2 (such as an EDM riser) without it cutting out

I am in the process of migrating my to Drumkv1 (from Fabla 1) for my band's live sampler and this limitation is making some samples impossible to use on Drumkv1. A single shot mode that plays the whole sample from start to finish and disregards the envelope would be great!

**Comment by rncbc** [comment]
@ViktorNova : try setting GEN Env.Time up or to "Auto" which makes for the whole sample time length.

**Comment by ViktorNova** [comment]
I had resorted to turning this knob up with got me most of the way there, but I did not realize there was an "Auto" mode!!! This is perfect, thank you! 

I have a few UI suggestions to make this more obvious to the user:

- Move the Env Time knob to the volume envelope section (makes more sense!)
- Add a checkbox to bypass the volume envelope, which would effectively just set the Env time to "Auto" and grey out the volume envelope controls in the UI
