### ISSUE TITLE
Save preset button is disabled

### ISSUE THREAD

**Issue by moritz157** [rncbc/drumkv1#15]
My problem is:
I loaded many samples into the current preset and wanted to save the preset, but the save button is disabled. Even if I create a blank .drumkv1 file and load it (which works fine), the button stays disabled.

**Comment by trebmuh** [comment]
Did you give a name to your preset ?
![drumkv1](https://cloud.githubusercontent.com/assets/8705846/24246253/c9ef0988-0fc6-11e7-8379-0c926a5ac7f6.png)
After giving it a name, the "Save Preset" button is activated here (drumkv1 0.8.1).

**Comment by moritz157** [comment]
LOL, problem fixed. Thank you :)

**Comment by trebmuh** [comment]
@moritz157 : glad it helps.
Would you mind closing this issue?
Happy music to you.
