### ISSUE TITLE
pad view and sequencer view

### ISSUE THREAD

**Issue by Reaper10** [rncbc/drumkv1#19]
I love drumkv1 it like the old school drum machine. To make drumkv1  to feel even more like an  old school drum machine you should add pad view and sequencer view.

pad view
The pad view is a page of on screen pad/buttons to trigger the drum sound. all pads should have a easy way to assign the note trigger under each pad. Next to that there should be a switch to switch form simple trigger pads to a pattern tigger that can be setup in sequencer view.

sequencer view
The sequencer view is a step sequencer/ drum machine like this
![dm1-32-steps](https://user-images.githubusercontent.com/8137561/35012100-1ebff574-face-11e7-8980-b65d71af9502.jpg)
In the sequencer view there should a way to see / select what pattern the user is in. Next to that should be a place to see what pad your on and what note tigger the  sequencer .

This would be useful with contorts like these
![htb1jk_ulfxxxxxtxvxxq6xxfxxxx](https://user-images.githubusercontent.com/8137561/35013240-5dbb8d84-fad2-11e7-922b-c655c4692794.jpg)
![j5mk panda200](https://user-images.githubusercontent.com/8137561/35013247-64180806-fad2-11e7-8dcf-77442cc3aa88.jpg)
![item_xxl_9630205_11075084](https://user-images.githubusercontent.com/8137561/35013262-6cee51a6-fad2-11e7-9e87-106dd8557ff7.jpg)

**Comment by rncbc** [comment]
sure a pad view and pattern sequencer would be extremely powerful additions to the humble drumkv1 :)

However, I still think they belong into yet another application level; you see, drumkv1 is not quite a "drum machine". it is more like a "drum sampler" or better yet, "drum rompler" :). Yes, it might be a perfect target for those MIDI controllers w/pads-and-knobs up there and of course driven by any MIDi sequencer as a host (LV2 plug-in) or as an external application (JACK client stand-alone), or even both ways.

cheers

**Comment by Reaper10** [comment]
if you don't like the idea feel free to close this

**Comment by rncbc** [comment]
@Reaper10 : it ain't about liking (or not) the idea--the idea is fine and truly welcome, believe me--just that (IMHO) it probably doesn't quite fit or belong to drumkv1 prospect (remember, doing some task and just that, nothing more than that?)
