### ISSUE TITLE
DrumkV1 doesn't load new preset in RaySession

### ISSUE THREAD

**Issue by sub26nico** [rncbc/drumkv1#20]
I have an issue with DrumkV1 with RaySession (https://github.com/Houston4444/RaySession).
I launched DrumkV1 et created a preset, then save my RaySession.
When I reload the session, I changed the DrumkV1 preset, then save preset and session.
At reload, DrumkV1 open the first preset, not the new. 
See https://github.com/Houston4444/RaySession/issues/5#issuecomment-364943870

**Comment by rncbc** [comment]
so it seems it's all about when and only under NSM ?

unfortunately i also can't reproduce this as you say.

well i've found something strange/fishy... stay tuned... nope. false alarm: all seems working as it should. maybe you can tell what exact steps leads to the wrong doing  that is:)

cheers

EDIT: there's one funny note that you must be aware though: when dealing NSM sessions, sample element names do have this hash/hex suffixes added... (they're the names of symlinks to the original sample filenames; but again, those symlinks do point to the actual sample files or don't they?

or wait, maybe you're saving a .drumkv1 preset _after_, or better said, _under_ a running NSM session? is that it?

**Comment by sub26nico** [comment]
yes

**Comment by rncbc** [comment]
yeah, that was the fishy smell i was sensing before ;)

it is anyway a good thing that someone is working out some of this... to be frank, i don't run NSM that often :S

**Comment by rncbc** [comment]
so may you test today's https://github.com/rncbc/drumkv1/commit/c6957ee82ab0d3a6334785236bf62fdeaf883fa5 ?

**Comment by sub26nico** [comment]
Thanks for the commit.
I've tested the today's c6957ee, DrumkV1 can load the preset loaded before stopping session 
but only if the preset is in the session folder. If I load a preset from anywhere else, it doesn't work
(at the next launch).
And I realize DrumkV1 rename the preset with the name of the session. 
For exemple, I create a Session (with Ray Session) called 'Test', with Drumkv1, Catia and Seq24.
In DrumkV1, I load samples and save the preset named 'Try' in my home , the preset is saved too 
in ~/NSM Sessions/Test/Test.drumkv1, and is called now 'Test.drumkv1'. So,  it seems to be not 
possible to load at the launch of the session a preset whom don't have the session's name and whom is not in the session folder.

**Comment by rncbc** [comment]
wait, the pseudo-preset file that drumkv1_jack saves under the NSM session directory is NOT supposed to be a regular preset whatsoever; if you're trying to load it from there you're doing it wrong!

please save your .drumkv1 presets outside the NSM Sessions tree, and at all costs NEVER open/load one from there, ever: those are in fact the NSM session state files and not quite a normal preset file for general consumption, outside a designated NSM session, no matter they share the same format and/or xml structure.

you may find that those NSM session state files, although with the same .drumkv1 suffix, do rely on local sym-links to target sample files, something that is only meaningful on that precise NSM session context.

please tell whether I'm being off topic here or else :)

cheers

**Comment by sub26nico** [comment]
You're not off topic, you're right.
cheers :)

**Comment by sub26nico** [comment]
I'm testing new release of Ray Session, and the situation seems to sound now as a good compromise.
Drumkv1 reload now the last preset saved in the session. Good point. 
The preset is still renamed by RaySession 'nameofthesession.drumkv1' 
in the (Ray) session's folder, but keeps in memory the (name of) presets already created/used 
before and stored in my own preset folder. So, it's easy to recall another preset if needed. 
For me it's usable and don't be an 'ergonomic non-sense' anymore. 
I ignore the part of enhancement from your side and from Houston4444's one, 
but once more, it's now very usable.  Thanks for the time given on this situation.
