### ISSUE TITLE
Under NSM, drumkv1 don't use system file picker even if option is checked

### ISSUE THREAD

**Issue by Houston4444** [rncbc/drumkv1#21]
launched under NSM, drumkv doesn't open system file pickers even if option is checked in "configure".
Uncheck and re-check this box make it works...until the next launch.

**Comment by rncbc** [comment]
Configure... > Options > "Use desktop environment environment dialogs" option has no or should not have any effect when under a NSM session; the generic QFileDialog must be shown at all times, again when under a NSM session.

There were situations when using the DE's native file-picker/browser/requester dialogs would hang and freeze the whole show (especially on gnome3, iirc.); also, the "Gtk" widget style themes (the default under Gnome, Xfce, etc.) is prone to issues when dealing the native file-open/save dialogs whatever.

What DE is yours?

**Comment by Houston4444** [comment]
My DE is KDE. 
I use drumkv last release (not master code).

I tried also running drumkv1_jack in a terminal, and I have not this issue, drumkv1 open well KDE file pickers !

**Comment by rncbc** [comment]
so it should work, presenting the stock file-dialog from Qt5... 

un-check that "use DE native dialogs" option and try again running drumkv1_jack, stand-alone ie. away from NSM session managers...

ps. also KDE5 / Plasma5.12, openSUSE Tumbleweed, Qt 5.10.0, x86_64 here in case it matters.

**Comment by Houston4444** [comment]
In standalone mode it works perfectly : Options > "Use desktop environment environment dialogs" is checked and I well have KDE file picker when I load audio file.

Under NSM, if I load a sound file, it opens QT File Dialog (and I don't like it, I have no shortcuts !). If I go to Options > "Use desktop environment environment dialogs", option is checked ! 
Uncheck and recheck make it works with KDE file pickers.

KDE /Plasma5.12 , Neon LTS Ubuntu 16.04 + KxStudio packages, Qt 5.9.3, x86_64 here.

**Comment by rncbc** [comment]
you may try from latest git head master (https://github.com/rncbc/drumkv1/commit/2f3011e) whether things are any better.

cheers && thanks

**Comment by Houston4444** [comment]
sorry, I can't build it. there is no configure file.
I tried `autoconf configure.ac` il doesn't make configure file.
I tried `autoconf`
It creates a configure file but when I run `./configure`
It says that wrong:
`./configure: line 3855: PKG_PROG_PKG_CONFIG: command not found`

There is no mention of autoconf in install or readme.md

**Comment by rncbc** [comment]
the instructions to build right after you clone from git head are the following:
`./autogen.sh` or `make -f Makefile.git`
that will make the `configure` script to appear in the build source tree :)
then the plain standard and usual ordeal follows:
```
./configure
make
sudo make install

```
hth
cheers
