### ISSUE TITLE
Under NSM, samplv1_jack opens a file dialog for sound file

### ISSUE THREAD

**Issue by Houston4444** [rncbc/drumkv1#22]
Under NSM, the first time you launch samplv1_jack, it opens a file picker(the good one this time !) to load a sound file. Why not !

Under NSM, save, stop samplv1_jack client, restart it, and it again loads a file picker (no need for it !). Finally, it doesn't matters what user is choosing with file picker, it re-choose the file chosen in the previous launch, weird !

**Comment by rncbc** [comment]
wrong project :)

anyway, you may test whether today's commit on git head master (https://github.com/rncbc/samplv1/commit/8e8762b) behaves any better.

cheers && thanks

**Comment by Houston4444** [comment]
Your Fix Works Perfectly, cheers &&  thanks !
