### ISSUE TITLE
DRUMKV1_LV2_URI

### ISSUE THREAD

**Issue by marado** [rncbc/drumkv1#23]
Currently, `DRUMKV1_LV2_URI` is defined as being `http://drumkv1.sourceforge.net/lv2`, that URI seems to present the same page as `http://drumkv1.sourceforge.net`. This creates a bunch of broken references (eg., for #ui, #ui_external, #state ...).

**Comment by rncbc** [comment]
Any LV2 URI is NOT, never was indeed a valid web or HTTP URL: it's meant to be unique global identifier. The fact that is prefixed by 'http://' is perfectly bogus.

The fact that http://drumkv1.sourceforge.net/lv2 points to some valid web site is just pure convenience; it used to go nowhere, splattering you into a 404 (which probably should have been always).

byee
