### ISSUE TITLE
Give *v1-jack save files under NSM a generic name to enable renaming and copying of the session

### ISSUE THREAD

**Issue by diovudau** [rncbc/drumkv1#24]
the session is named "tutorial". so there is

 ~/NSM Sessions/tutorial/drumkv1.nEGYA/tutorial.drumkv1

What I am asking you is to save and load the last part, the basename of
your drumkv1 file, under just "save.drumkv1" or something generic.

Why is the current behaviour not as optimal as it could be?

You can copy the whole session

cd "NSM Sessions"
cp -r tutorial  bestsong

That is the same as using the "Duplicate" button in the NSM GUI.

Now V1 software, when opened in "bestsong" looks for

 ~/NSM Sessions/bestsong/drumkv1.nEGYA/bestsong.drumkv1
 
but bestsong.drumkv1 does not exist, only  ~/NSM
Sessions/bestsong/drumkv1.nEGYA/tutorial.drumkv1

Always using "save.drumkv1"  solves this problem and introduces no other
problems because the filepath is still unique, thanks to the parent
directory drumkv1.nEGYA/

**Comment by rncbc** [comment]
now saving to "session.drumkv1" file, as of https://github.com/rncbc/drumkv1/commit/653c106 ...

please test && tell

**Comment by diovudau** [comment]
I tested drumkv1 from git and the problem is fixed. Renaming the session and making a copy of it is now possible. 
Thank you very much!
