### ISSUE TITLE
Store NSM GUI hidden / visible status in the save file and restore state on session start

### ISSUE THREAD

**Issue by diovudau** [rncbc/drumkv1#25]
I would like to ask that the v1 suite remembers its GUI state in its save file and starts up as hidden if the session was closed with the program hidden.

I've asked NSM upstream and they say this is the responsibility of the clients themselves, and not the session manager.

**Comment by rncbc** [comment]
not quite about storing GUI visibility state but not showing it initially when under NSM : https://github.com/rncbc/drumkv1/commit/17952bc

iow. you'll now need to show it explicitly from the session manager!

**Comment by diovudau** [comment]
That is a good default. I am satisfied :)
