### ISSUE TITLE
v1 suit does not react to SIGTERM properly, therefore produces Xruns and hangs Jack 

### ISSUE THREAD

**Issue by diovudau** [rncbc/drumkv1#26]
the v1 suite seems to have no code for handling sigterm and sigint. 
Especially sigterm is used by session managers to send a quit signal.

For a single program *v1_jack produces Xruns, jack message like this:

```
11:05:28.599 XRUN callback (1).
JackEngine::XRun: client = padthv1.nQTWD was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = padthv1.nQTWD was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
11:05:28.606 ALSA connection graph change.
11:05:28.610 JACK connection graph change.
port deleted: padthv1-nQTWD:midi/capture_1
11:05:28.778 JACK connection change.
11:05:28.779 ALSA connection change.
11:05:28.780 XRUN callback (1 skipped).
```

Under the "right" circumstances, if all v1 programs receive sigterm at the same time, this can leave other jack clients hanging for up to 30 seconds and freezes jack and qjacktctl in the meantime.

**Comment by rncbc** [comment]
probably fixed on https://github.com/rncbc/drumkv1/commit/9147e3e

cheers

**Comment by diovudau** [comment]
I can confirm that all vee one programs now exit properly.
