### ISSUE TITLE
Lv2 plugin UI is failed to initialize in Ardour5 

### ISSUE THREAD

**Issue by ArtemPopof** [rncbc/drumkv1#27]
I tried to use drumkv1 with Ardour 5.12, obtained from kxstudio repo. I installed drumkv1 also from kxstudio repo, but drumkv1 plugin ui is not shown in Ardour. Ardour log says following:  [ERROR]: failed to instantiate LV2 GUI. I also tried install drumkv1 from sources, but it makes no difference.

**Comment by rncbc** [comment]
this is a problem specific to Ardour and whether it's linked to a recent libSUIL >= 0.10.2.

there's nothing about the upstream drumkv1 source or build that helps you here.
however, you should have read these [ps. words of advice for ardour users...](https://www.rncbc.org/drupal/node/1918#ardour).

hth.
cheers
