### ISSUE TITLE
drumkv1 inside Qtractor: cannot enter values in input fields with keyboard

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/drumkv1#32]
commit b83834e842a7abb44595c61f056f5820bfe0dc1c breaks it
    "Yet again, got rid of LV2UI::Qt5 as an option"

commit 377e7b33ec167d4000b0258cf659dbdd7427e44c is OK

**Comment by rncbc** [comment]
commit https://github.com/rncbc/drumkv1/commit/b83834e is/was intentional, mainly for coping with Ardour's stance against the so called 'big toolkits' ...

it can edit your own `drumkv1.ttl` if it pleases you  :)

**Comment by suedwestlicht** [comment]
Thx. Reverting the removal does the trick.

```
- lv2ui:ui drumkv1_lv2:ui_x11, drumkv1_lv2:ui_external ;
+ lv2ui:ui drumkv1_lv2:ui, drumkv1_lv2:ui_x11, drumkv1_lv2:ui_external ;
```

Don't you have this bug in your Qtractor/drumkv1 environment? I have it even with Qt 5.14.

**Comment by rncbc** [comment]
> Don't you have this bug in your Qtractor/drumkv1 environment? I have it even with Qt 5.14.

nope i have not, but I remember it occurring a couple of years ago when using the LV2UI:X11 of course

but again all my desktop stack is bleeding edge opensuse-tumbleweed :)...

cheers

ps. can you try to rebuild qtractor with `./configure --disable-libsuil` and test again with original drumkv1.lv2 ? just to check on some ideas i have lurking around here :)

**Comment by suedwestlicht** [comment]
Disabling libsuil makes the bug vanish as well.

I have libsuil 0.8.2 from kxstudio. Shall I compile recent 0.10.6?

**Comment by rncbc** [comment]
you've found the culprit! :)

**Comment by suedwestlicht** [comment]
Yes and no.

All new lv2, serd, sord, sratom, suil, lilv and the bug is still there. I have to tweak drumkv1's ttl-file.

And `./configure --disable-libsuil` doesn't help anymore.

lv2-1.16.0
lilv-0.24.6
serd-0.30.2
sord-0.16.4
sratom-0.6.4
suil-0.10.6

Qt 5.14.2

Qtractor starts slower (half a second with a non-drawn main window).
But: With those new lv2 and libs a big Qtractor project with CPU-hungry plugins only uses 2/3 of the realtime CPU. That's a big win.

**Comment by suedwestlicht** [comment]
The intermittent performance boost seems to have itself stabilized after a reboot.

But one effect of the new libs seems to be that after loading a song it's immediately marked dirty (save icon is active).

**Comment by rncbc** [comment]
in an alternative you can also test whether having **libsuil-x11-in-qt5** or what is called in your distro installed or not makes a difference -- having libsuil-x11-in-qt5 removed might lead to the same results as a qtractor `./configure --disable-libsuil` build, modulo some message like `suil error: Failed to open module libsuil_x11_in_qt5.so` in the output...

**Comment by suedwestlicht** [comment]
I can live with it. Maybe it fixes itself magically sometimes, maybe after a distro upgrade.
