### ISSUE TITLE
Failed to instantiate LV2 (ardour)

### ISSUE THREAD

**Issue by m4l3z** [rncbc/drumkv1#34]
Hi rncbc hope you're doing well,
I reinstalled a workstation with your plugins but didn't manage to have any of the vee suite working as lv2 plugins on ardour with this message "[ERROR]: LV2: Failed to instantiate plugin http://drumkv1.sourceforge.net/lv2"
I compiled them from source with all flags checked as "yes". I tried the three last version including the fall release (thanks btw)
The plugins load under carla with no issue whatsoever. I tried to do the ui quick hack in the manifest with no luck. I'm using ardour 5.12.0-1kxstudio2v5.
Do you have any clue what could be wrong ?
Take care,

**Comment by rncbc** [comment]
please compile or run drumkv1-lv2 (or any of the vee-ones) on the same system as ardour, or build against statically linked Qt5 libraries; you can find the latter on a one of mine PPAs (https://launchpad.net/~rncbc); choose wisely according to your distro series; eg. xUbuntu 20.04 (focal):

`sudo add-apt-repository ppa:rncbc/focal`
`sudo apt-get update`

from this moment all the most bleeding-edge qstuff is there ready for you to just install at will, including all the vee-ones properly build as above:

`sudo apt-get install drumkv1-lv2`

or , if you wish to compile yourself:

`sudo apt-get install qtbase5-static`

for each time you wish to build it as usual, remember to call this first:

`source /opt/qtbase5-static/*/bin/qtbase5-static-env.sh`

`./configure `... 
`make`
`sudo make install`

hth
cheers

**Comment by m4l3z** [comment]
Thanks a lot for the answer rncbc !
I reinstalled qtbase5-static (it was missing) and your own ppa.
When I installed drumkv1-lv2 from your repo, the lv2 would load but the UI would failed to instantiate.
When I try to compile it myself, the plugin wont load at all (under ardour).
I didn't manage to find the qtbase5-static-env.sh file so I compiled without that step.
Still no luck.

_happy that I added your ppa nonetheless_
cheers,
m4

**Comment by rncbc** [comment]
> didn't manage to find the qtbase5-static-env.sh file so I compiled without that step.

than it cannot ever be compiled to qtbase5-static ever. and thus it still won't work on that ardour anyway.

please make sure `atbase5-static ` and all its dependencies are installed properly and find the de said file in correct path below, as the time of this writing:
`/opt/qtbase5-static/5.15.1/bin/qtbase5-static-env.sh`

otoh. before a new `drumkv1-lv2` gets to work at all, you'll certainly need to remove ALL traces of ANY previous drumkv1 installations , more importantly if they were done from source. look for those traces under `~/.lv2`,  `/usr/local/lib/lv2` or else `/usr/lib/lv2` where the `drumkv1-lv2` package should be.

**Comment by m4l3z** [comment]
Even tho I installed qtbase5-static, I cannot find the proper bash script, it doesn't seem to be anywhere.
I might just use a hack with carla rack for now. Thanks for the guidance :)

**Comment by rncbc** [comment]
wait. what gives `ls -l /opt` ?
if it ain't `/opt/qtbase5-static` listed then you don't have it installed for sure.

**Comment by m4l3z** [comment]
It showed nothing BUT I finally managed to add your repository (it didn't contain a proper Release file for bionic so I had to add insecure repositories) and now it's working after installing drumkv1 directly from your ppa !! Thanks a lot man :)
