### ISSUE TITLE
add distortion effect?

### ISSUE THREAD

**Issue by grammoboy2** [rncbc/drumkv1#35]
I'm not a drumsynth expert, but do I miss a distortion effect? :)

**Comment by rncbc** [comment]
there's none.

you can of course edit and apply any distortion to them prior to loading the samples to drumkv1; or after as an audio-fx plugin. your call.

**Comment by grammoboy2** [comment]
Sure, that's what I did. But the same it true for the other effects you've added... ;) See it as feature request, feel free to ignore.
