### ISSUE TITLE
sfz or h2kit support?

### ISSUE THREAD

**Issue by grammoboy2** [rncbc/drumkv1#36]
Is there sfz or h2kit (hydrogen) support?

If not, looks handy to me, when you can load a simple sfz file.

Edit: a script to make a drumkit file from a folder of samples, where you can specify the starting key like makesfz script, will do too probably.

**Comment by rncbc** [comment]
nope. 

however there are other ways eg. https://github.com/TuriSc/hydrogen2drumkv1.py/

**Comment by grammoboy2** [comment]
Thanks. So convert a folder to a hydrogen drumkit and then convert it to drumkv1...
Can't 'we' all switch to sfz?! :) 

Fyi
https://github.com/swesterfeld/liquidsfz

edit: Something like TAL sampler has also SFZ support for example https://tal-software.com/products/tal-sampler
