### ISSUE TITLE
warning: expression result unused

### ISSUE THREAD

**Issue by yurivict** [rncbc/drumkv1#39]
Version 0.9.20 prints the warning on FreeBSD 12,2:

```
/usr/ports/audio/drumkv1-lv2/work/drumkv1-0.9.20/src/drumkv1_jack.cpp:731:42: warning: expression result unused [-Wunused-value]
        (::write(g_fdSigterm[0], &c, sizeof(c)) > 0);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
1 warning generated.
```

clang-10

**Comment by rncbc** [comment]
please ignore the warning, it's innocuous

**Comment by yurivict** [comment]
What would happen if ```write``` would return the failure error code (-1)?

**Comment by rncbc** [comment]
> What would happen if `write` would return the failure error code (-1)?

sigterm won't get handled properly, but quite unlikely to occur
