### ISSUE TITLE
Is the drag and drop feature working?

### ISSUE THREAD

**Issue by mene311** [rncbc/drumkv1#40]
I'm running KDE on Arch (fwiw) and I can't seem to get to drag and drop to work

**Comment by rncbc** [comment]
yes, it should work, at least as long it's running on xcb premises; not so sure on wayland :(

**Comment by mene311** [comment]
Hi yes, I just checked and it's a matter of the host (in this case zrythm) at least. On a standalone instance, it is allowed to drag and drop just fine.
