### ISSUE TITLE
[Vee One Suite] Tiling windows

### ISSUE THREAD

**Issue by grammoboy2** [rncbc/drumkv1#44]
Just a quick note, when using a tiling WM, some parts of the synth (waveform) get weird shaped. Don't know if that could be easily solved. Maybe something to keep in the back of your head somewhere. 
Cheers.

**Comment by rncbc** [comment]
preventing the window from being managed by the tiling wm is the best hint I can give

ps. maybe this thread is of any help: https://www.rncbc.org/drupal/node/2352
