### ISSUE TITLE
Plugin loses keyboard focus in Reaper

### ISSUE THREAD

**Issue by KottV** [rncbc/drumkv1#45]
Hi,

It looks like a focus/window stacking bug, but I'm not sure where exactly. The same is for the other Qstuff plugins. (Reaper is free for evaluating).

1. Start Reaper.
2. Optionally check LV2 path in Preferences and scan for plugins.
3. Add a track, add drumkv1 to the FX.
4. Try to set any value in the Effect tab with keyboard, it should work.
5. Change the window focus anywhere or load a sample inside plugins.
6. Try to input any value with keyboard in parameters, it doesn't work.

I checked with Qt logging option:
`~/.config/QtProject/qtlogging.ini`:
```
[Rules]
*.debug=false
```
Indeed, every keyboard events weren't received, all pressed keys go to the Reaper's plugin parent frame.

**Comment by rncbc** [comment]
unfortunately this is mostly a system environment issue; it also depends on the particular plugin build--the here upstream recommendation is that qt6.4-static builds might work better in that regard and others overall

may I ask how your drumkv1-lv2 was provided? packaged, built from source and in any case which distro?

**Comment by KottV** [comment]
Completely forgot to fill that.
openSUSE TW, KDE Plasma

Reported behavior is for local build from source with Qt6 dynamically linked.
With `synthv1-lv2` from your repo `home:rncbc` I can't change parameters values even with the new plugin window instance.

**Comment by rncbc** [comment]
then it must be something with Reaper :( for instance, Ardour and your truly Qtractor don't seem to suffer

here using TW and Plasma5 as well :)
