### ISSUE TITLE
Ability to bypass filter

### ISSUE THREAD

**Issue by ViktorNova** [rncbc/drumkv1#7]
It would be really nice to be able to switch the filter off per sample to bypass it completely!

**Comment by rncbc** [comment]
@ViktorNova : setting DCF Envelope to 0% might do what you ask.

**Comment by ViktorNova** [comment]
I am finding that this helps the filter not to change in time, but it does not address what perhaps is a bigger problem, which is that is seems currently _impossible_ in Drumkv1 to play a sample and not have it colored by the filter in some way. 

The LPF filter, for example, even with the cutoff turned up all the way and envelope at zero, is still cutting a fair amount of high end out of the sample. I'm in the process of importing a sizable sample library into Drumkv1 and on every sample I have to make a choice on what to sacrifice for that sample - "Do I want to lose some high end, or do I want to lose some low end?" 

This is not quite a show stopper because most samples could stand to have either the extreme highs or extreme lows attenuated, but it would be great to just be able to check a box to disable the filter altogether and not have to sacrifice anything. Also I imagine this would improve performance somewhat, especially on low-power machines like the Raspberry Pi
