### ISSUE TITLE
GM drum names should be replaced with note names

### ISSUE THREAD

**Issue by ViktorNova** [rncbc/drumkv1#9]
This is a major usability issue in Drumkv1. Having the GM drum names in there doesn't really make sense for these reasons:

- Most people do not use GM anymore
- It obscures the actual note names, which makes it hard on the user to map those samples
- It seems arbitrary

**Comment by rncbc** [comment]
@ViktorNova : actual note names are displayed whenever GM drum key names are not defined; yes, remember that is is so called "old-school" being GM/GS/XG a part of the "old" adjective ;)

Custom drum key names configuration is planned but fallen victim of chronic procrastination. 

Anyways, thanks for the heads-up!

**Comment by ViktorNova** [comment]
I know you call it an "old-school" drum sampler, but I would argue that Drumkv1 is a a very competent modern drum sampler that is unrivaled by anything available on Linux at the moment!!  Really there is nothing out there as good, with all the features, etc.

I believe forcing the GM placeholder names in there (with no way to change them or show the actual note names) hiders usability for what is probably the majority of users. I think the GM drumkit is kind of a niche market these days that only a few people still use in practice, and additionally, even if someone wanted to build a GM kit in Drumkv1, doing so may still be difficult because the note names are obscured by the GM placeholder names, making it still non-intuitive to put the samples in the right place. This is coming from someone preparing to use Drumkv1 in production. =) It's great, I love it! And want to help it improve

I made a slight modification that displays all of the note names in place of the GM placeholder names and am putting together a proper pull request, I hope you will consider merging it in light of the points I brought up! (perhaps a future compromise would be to have a built-in non-default preset that has the GM names in the Sample Name field and keeps them there until a sample is loaded?)

**Comment by ViktorNova** [comment]
This is now fixed in options, so I'm closing it
